language: node_js
node_js:
  - "7"
  - "8"
  - "9"

before_install:
  - npm install -qg npm
  - npm install -qg grunt-cli

script:
  - grunt mochaTest
  - grunt run:coverage

after_script:
  - grunt coveralls
