language: node_js

cache:
  directories:
    - .yarn/cache

# This stops the entire job from running if it's a PR
if: type != pull_request

node_js:
  - '20'
  - '22'
  - '25'

before_install:
  - corepack enable

install:
  - yarn install --immutable

script:
  - yarn test
